"""
Assign one icon set to every category (image = /sites/lienstore/shared/categories/icons/<set>/<slug>.png).

  python scripts/xlsx/apply_category_icons.py 3d        # Bộ A · Fluent Emoji 3D
  python scripts/xlsx/apply_category_icons.py flat      # Bộ B · Noto Emoji
  python scripts/xlsx/apply_category_icons.py line      # Bộ C · Tabler line icons in a green circle
  python scripts/xlsx/apply_category_icons.py flat2     # Bộ D · Fluent Emoji Flat
  python scripts/xlsx/apply_category_icons.py 3d --only the-bai-pokemon,do-choi-suu-tap   # just some slugs
  python scripts/xlsx/apply_category_icons.py 3d --keep-uploaded                             # leave hand-uploaded images alone

PNGs are generated by the icon-set script (300×300, white background); regenerate them if a new category is added.
"""
import argparse, datetime, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SEED = ROOT / "data" / "seed.json"
WEB = "/sites/lienstore/shared/categories/icons"

ap = argparse.ArgumentParser()
ap.add_argument("set", choices=["3d", "flat", "line", "flat2"])
ap.add_argument("--only", help="comma-separated slugs")
ap.add_argument("--keep-uploaded", action="store_true", help="do not replace images under /uploads/ (set by hand in the admin)")
args = ap.parse_args()

seed = json.loads(SEED.read_text(encoding="utf-8"))
only = set(args.only.split(",")) if args.only else None
changed = 0
for c in seed["categories"]:
    if only and c["slug"] not in only:
        continue
    png = ROOT / "public" / WEB.lstrip("/") / args.set / f"{c['slug']}.png"
    if not png.exists():
        print("no png for", c["slug"])
        continue
    if args.keep_uploaded and (c.get("image") or "").find("/uploads/") >= 0:
        continue
    c["image"] = f"{WEB}/{args.set}/{c['slug']}.png"
    changed += 1
seed["meta"]["seededAt"] = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
SEED.write_text(json.dumps(seed, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
print(f"set {args.set} → {changed} categories")
